### ISSUE TITLE
Code Samples not work

### ISSUE THREAD

**Issue by gillgill12** [dukedhx/viewer-flutter-dart#1]
Hi 
i clone the sample code and put the svf model to the "assets" folder and change the URL in assets/index.html
run on emulators get Blank screen.

```
Flutter version: 2.3.0-17.0.pre.121
OS: mac big sur
Simulator: iPhone 12 - ios 14.5
```

also i try set up a timer for the webview 
 
Any ideas?

**Comment by SalarPro** [comment]
Update all pub libraries, 
If you have problems with android or iOS folder delete them, then run `flutter create .`

This is for flutter 3.16.3


pubspec.yaml
```
dependencies:
  cupertino_icons: ^1.0.6
  flutter:
    sdk: flutter
  flutter_launcher_icons: ^0.13.1
  flutter_webview_plugin: ^0.4.0
  jaguar: ^3.1.3
  jaguar_flutter_asset: ^3.0.0
```
